configs:
  apt:
    file: './configs/debian.sources'
  ccache:
    file: './configs/ccache.conf'
name: 'docker-on-android'
services:
  build:
    build:
      additional_contexts:
        configs: './configs'
      context: '.'
      target: 'source'
    configs:
      - source: 'apt'
        target: '/etc/apt/sources.list.d/debian.sources'
      - source: 'ccache'
        target: '/etc/ccache.conf'
    environment:
      ANDROID_ADB_SERVER_ADDRESS: 'host.docker.internal'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    init: true
    network_mode: 'none'
    volumes:
      - './out:/home/build/out'
